config/routes.rb
Rails.application.routes.draw do
  get 'notifications/destroy'
  devise_for :users
  root to: 'pages#home'
  resources :applications do
    resources :applications_documents, only: [:new, :create]
  end
  resources :universities_programs do
    resources :applications, only: [:new, :create]
  end

  resources :notifications, only: [:destroy]
  resources :applications_documents, only: [:destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container-fluid footer-body">
  <div class="container">

  </div>
</div>

app/views/shared/_navbar.html.erb
<%if user_signed_in?%>
<%@notifications = Notification.all%>
<% end %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container" style="padding: 0;">
  <%= link_to "/", class: "navbar-brand" do %>
    <h2 style="font-family: 'Permanent Marker', cursive;">UNI<span style="color:#8992FF;">Find</span></h2>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
          <%= link_to "Programs", "/universities_programs", class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <div id=notifications-counter></div>
          <li class="nav-item dropdown this-one">
            <% if current_user.notifications == []%>
              <%= image_tag "https://cdn.pixabay.com/photo/2015/12/16/17/41/bell-1096279_960_720.png", class: "notification dropdown-toggle", id: "notification-dropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>

              <%= image_tag "https://cdn.pixabay.com/photo/2015/12/16/17/41/bell-1096279_960_720.png", class: "notification dropdown-toggle", id: "notification-dropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right diese-hier p-1" id="dropdown-count" aria-labelledby="navbarDropdown">
              <% if current_user.notifications == []%>
                <div>
                  No notifications
                </div>
              <% else %>
                <% @notifications.each do |notification|%>
                  <%if notification.application.user_id == current_user.id%>
                    <div class = "notifications-content d-flex flex-row align-items-center p-2 m-2" style="border-radius:8px;color:#121E72;background:white" >
                      <div>
                        <%= image_tag(notification.application.universities_program.picture, style: "border-radius:8px;width:100px;height:63px;object-fit:contain;margin-right:8px;") %>
                      </div>
                      <%= notification.content%>
                      <%= link_to "/applications", method: :get do %><i class="fas fa-search mx-2" style="color:#6C77FF"></i></i><% end %>
                      <%= link_to notification_path(notification), method: :delete do %><i class="fa fa-times" style="color:red;"aria-hidden="true"></i><% end %>
                    </div>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </li>
          <div id=notifications-counter></div>
        <li class="nav-item dropdown">
          <%= image_tag "https://res.cloudinary.com/donatadietz/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1591834465/IMG_5184_zhmz8z.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", "#", class: "dropdown-item" %>
            <%= link_to "My applications", "/applications", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", "/users/sign_up", class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
</div>

<script>
var results = document.getElementById("notifications-counter");
var count = document.getElementById("dropdown-count").childElementCount;
var x = document.querySelectorAll(".notifications-content").length;

if (x > 0) {
  results.insertAdjacentHTML("beforeend", x);
}


</script>