config/routes.rb
Rails.application.routes.draw do
  get 'notifications/destroy'
  devise_for :users
  root to: 'pages#home'
  resources :applications do
    resources :applications_documents, only: [:new, :create]
  end
  resources :universities_programs do
    resources :applications, only: [:new, :create]
  end

  resources :notifications, only: [:destroy]
  resources :applications_documents, only: [:destroy]
end

app/models/universities_program.rb
class UniversitiesProgram < ApplicationRecord
  belongs_to :program
  belongs_to :university
  has_many :applications, dependent: :destroy
  has_many :universities_programs_documents, dependent: :destroy
  has_many :documents, through: :universities_programs_documents, dependent: :destroy
end

app/controllers/universitiesPrograms_controller.rb
class UniversitiesProgramsController < ApplicationController
  before_action :set_universities_program, only: [ :show, :edit, :update, :destroy ]

  def index
    if params[:query].present?
      sql_query = " \
      universities_programs.discipline ILIKE :query \
      OR programs.name ILIKE :query \
      "
      @universities_programs = UniversitiesProgram.joins(:program).where(sql_query, query: "%#{params[:query]}%")
    else
      @universities_programs = UniversitiesProgram.all
    end
  end

  def show
    @application = Application.new
  end

  private

  def set_universities_program
    @universities_program = UniversitiesProgram.find(params[:id])
  end

  def universities_program_params
    params.require(:universities_program).permit(:university_id, :program_id, :programs_documents_id, :quota, :degree, :webpage_url, :discipline, :language, :semesters, :deadline)
  end
end

app/controllers/universities_programs_controller.rb
class UniversitiesProgramsController < ApplicationController
  before_action :set_universities_program, only: [ :show, :edit, :update, :destroy ]
  def index
    if params[:query].present?
      sql_query = " \
      universities_programs.discipline ILIKE :query
      OR programs.name ILIKE :query
      OR universities.name ILIKE :query
      OR universities_programs.degree ILIKE :query
      "
      @universities_programs = UniversitiesProgram.joins(:program, :university).where(sql_query, query: "%#{params[:query]}%")
    else
      @universities_programs = UniversitiesProgram.all
    end
  end

  def show
    @application = Application.new
    @uniphotos = @universities_program.university.photo_urls
  end

  private

  def set_universities_program
    @universities_program = UniversitiesProgram.find(params[:id])
  end

  def universities_program_params
    params.require(:universities_program).permit(:university_id, :program_id, :programs_documents_id, :quota, :degree, :webpage_url, :discipline, :language, :semesters, :deadline)
  end

  def skip_pundit?
    true
  end
end

app/views/universities_programs/index.html.erb
<div class="container mt-4" style="min-height:100vh;">
  <div class="row">
    <div class="col-3 left-frame border-top border-primary ">
      <div class="w-100">
        <h5>Search</h5>
        <div>
          <%= form_tag universities_programs_path, method: :get do %>
          <%= text_field_tag :query,
          params[:query], :class => "home-search-input w-100 mb-2", placeholder: "Program Name"%>
          <%= submit_tag "Search", class: "btn btn-block primary-btn " %>
          <% end %>
        </div>
      </div>

      <div class="w-100">
        <h6 class=>Most searched programs:</h6>
        <label class="tag-label"><a href= "/universities_programs?query=medicine"  >Medicine</a></label>
        <label class="tag-label"><a href= "/universities_programs?query=engineering"  >Engineering</a></label>
        <label class="tag-label"><a href= "/universities_programs?query=archeology" >Archeology</a></label>
        <label class="tag-label"><a href= "/universities_programs?query=product+design" >Product Design</a></label>
        <label class="tag-label"><a href= "/universities_programs?query=literature"  >Literature</a></label>
        <label class="tag-label"><a href= "/universities_programs?query=pteaching"  >Teaching</a></label>
        <label class="tag-label"><a href= "/universities_programs?query=architecture"  >Architecture</a></label>
        <label class="tag-label"><a href= "/universities_programs?query=economics" >Economics</a></label>
      </div>
    </div>

    <div class="col-9 pl-3 mb-5 pr-0 ">
      <div class="col-12 border-top " style="background-color: #F3F4FF; border-radius: 6px; padding-bottom: 32px;">
        <div class="row mx-2">
          <h5 id=num_results class= "mt-2"></h5>
        </div>
        <div class="row mx-2 mb-0">
        </div>
        <div id=all_programs class="col-12 pl-3 pr-3 pt-0" >
          <% @universities_programs.each do |program|%>

          <%= link_to "universities_programs/#{program.id}" do %>
          <div class="card-product  mt-3 col-12 pl-0 d-flex flex-row text-center transition1 grow" style="border-radius: 4px" >
            <div class="color-add">
            <div class="logo">
              <%= image_tag(program.picture, style: "width: 150px;height:120px;object-fit:contain;") %>
            </div>
            </div>
            <div class="col-7 text-left " style="line-height: 150%;">
              <h3 style="margin-bottom: 8px;"><%= program.university.name %></h3>

              <label class="tag-label"><%= program.program.name%></label>
              <h3 id="degree" style="font-size: 14px;"><%=program.degree%></h3>
            </div>
          </div>
          <%end%>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>


<script>
  var results = document.getElementById("num_results");
  var count = document.getElementById("all_programs").childElementCount;
  insertion = ""
  if (count === 1){
    insertion = `${count} result found`
  } else {
    insertion = `${count} results found`
  }
  results.insertAdjacentHTML("afterbegin", insertion)


</script>

app/views/universities_programs/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <script src="https://kit.fontawesome.com/9bc9c7a1c8.js" crossorigin="anonymous"></script>
</head>
<body>


  <div class="container mt-4">
    <div class="row">
      <div class="col-4 border-top border-primary pr-0 mr-0" id="application-info">

       <div class="card-application">
        <br>
        <h2 style="display: inline"><%= @universities_program.university.name %></h2>
        <br>
        <br>
        <label class="tag-label" style="padding: 8px 16px; font-size:18px;"><%=@universities_program.program.name%></label>
        <br>
        <br>
        <br>
        <br>
        <h5> <i class="fad fa-map-marked-alt"></i> <%=@universities_program.university.city%></h5>
        <h5> <i class="fad fa-calendar"></i> <%= @universities_program.semesters %> Semesters</h5>
        <h5> <i class="fad fa-graduation-cap"></i> <%= @universities_program.degree %></h5>
        <br>
        <br>
        <br>
        <% if @universities_program.applications.where(user_id: current_user.id) == []%>
        <%= form_tag applications_path, method: :post do %>
        <%= hidden_field_tag "application[universities_program_id]", @universities_program.id %>
        <%= button_tag class: "btn primary-btn" do %>
        Apply now <i class="fad fa-layer-plus ml-2"></i>
        <%end%>
        <% end %>
        <% else %>

        <%= link_to "/applications" do %> <button class="btn primary-btn">See on Dashboard</button> <% end %>

        <% end %>
      </div>
    </div>

    <div class="col-8 pr-0 ml-0" id="carousel">
      <div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active" data-interval="3000">
            <%= image_tag(@universities_program.university.photo_urls[0]) %>
          </div>
          <div class="carousel-item" data-interval="3000">
           <%= image_tag(@universities_program.university.photo_urls[1]) %>
         </div>
       </div>
       <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>

</div>
<div class="row transition1" id="show-row">
  <div class="col-12 border-top" id="uniinfo">
    <h3 style="font-size: 22px;">Learn more about the faculty</h3>
    <p style="font-size: 16px;"><%= @universities_program.university_info %></p>
    <a href= "<%= @universities_program.webpage_url %>" target="_blank"><label class="btn secondary-btn">Official Page</label></a>
    <br>
    <br>
    <h3 style="font-size: 22px;" >What it's like to study architecture at our university</h3>
    <p style="font-size: 16px;"> <%=  @universities_program.application_info %> </p>

    <label class="secondary-btn"><a style="margin-bottom: 40px;" href="<%= @universities_program.application_url %>" target="_blank">Application Site</label></a>

  </div>
</div>
<a id="buttonshow" href="/universities_programs">← Back to all Programs</a>
</div>

</body>
</html>